name = "lecture-folder-app"
compatibility_date = "2024-04-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "lecture-app-db"
database_id = "e07e9bc712f30dde987c0959b76939ff" # Production ID

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "lecture-app-files"

[vars]
ENVIRONMENT = "development"
